---
language: python
sudo: required

# whitelist
branches:
  only:
    - master

services:
  - docker

before_install:
  # update ubuntu packages
  - sudo apt-get -qq update

install:
  - pip install tox-travis

script:
  - tox
