---
language: python
sudo: required

python:
  - "3.7"

# whitelist
branches:
  only:
    - master

services:
  - docker

before_install:
  # update ubuntu packages
  - sudo apt-get -qq update

install:
  - pip install tox-travis

script:
  - tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
